<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE TEMPLATECOLLECTION [

<!ELEMENT TEMPLATECOLLECTION (TEMPLATE)*>

<!ELEMENT TEMPLATE (FILE_NAME, DEPENDENCIES, DEPENDENCY_COUNT, THIRD_PARTY_DEPENDENCIES, DESCRIPTION, FEED_URL, IMPORTS, ARGS)>

<!ATTLIST TEMPLATE 

NAME CDATA #REQUIRED

>

<!ELEMENT FILE_NAME (#PCDATA)>

<!ELEMENT DEPENDENCIES (DEPENDENCY)*>

<!ELEMENT DEPENDENCY (#PCDATA)>

<!ELEMENT DEPENDENCY_COUNT (#PCDATA)>

<!ELEMENT THIRD_PARTY_DEPENDENCIES (EXT_DEPENDENCY)*>

<!ATTLIST THIRD_PARTY_DEPENDENCIES 

ISREQUIRED CDATA #REQUIRED

>

<!ATTLIST EXT_DEPENDENCY 

NAME CDATA #REQUIRED

>

<!ELEMENT DESCRIPTION (#PCDATA)>

<!ELEMENT FEED_URL (#PCDATA)>

<!ELEMENT IMPORTS (IMPORT)*>

<!ELEMENT IMPORT (#PCDATA)>

<!ELEMENT ARGS (ARG)*>

<!ELEMENT ARG (#PCDATA)>

]>

<TEMPLATECOLLECTION>



	<TEMPLATE NAME="Spreadsheet">
		
		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
		  <DEPENDENCY>^gdata\-spreadsheet(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
		  
		  <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
		  
		  <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
		  
		  <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>

    </DEPENDENCIES>
		
		<DEPENDENCY_COUNT>6</DEPENDENCY_COUNT>
		
		<THIRD_PARTY_DEPENDENCIES ISREQUIRED="False">
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>This template creates a console application which interacts with the Google Spreadsheets Data API to retrieve a list of all Google Spreadsheets for a particular user.</DESCRIPTION>
		
		<FEED_URL>http://spreadsheets.google.com/feeds/spreadsheets/private/full</FEED_URL>
		
		<IMPORTS>
		
		  <IMPORT>com.google.gdata.client.spreadsheet.SpreadsheetService</IMPORT>

      <IMPORT>com.google.gdata.data.spreadsheet.SpreadsheetEntry</IMPORT>
    		
      <IMPORT>com.google.gdata.data.spreadsheet.SpreadsheetFeed</IMPORT>
    
		</IMPORTS>
		
		<ARGS>
		
		  <ARG>username</ARG>
		  
		  <ARG>password</ARG>
		
		</ARGS>
		
	</TEMPLATE>


	<TEMPLATE NAME="Base">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-base\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>

		<DEPENDENCY_COUNT>5</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="True">
    
      <EXT_DEPENDENCY NAME="Activation.jar">^activation(\-[1-9](\.[0-9])?(\.[0-9])?)?\.jar$</EXT_DEPENDENCY>
      
      <EXT_DEPENDENCY NAME="Mail.jar">^mail(\-[1-9](\.[0-9])?(\.[0-9])?)?\.jar$</EXT_DEPENDENCY>
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>abcd</DESCRIPTION>

		<FEED_URL>http://spreadsheets.google.com/feeds/spreadsheets/private/full</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.spreadsheet.SpreadsheetService</IMPORT>

			<IMPORT>com.google.gdata.data.spreadsheet.SpreadsheetEntry</IMPORT>

			<IMPORT>com.google.gdata.data.spreadsheet.SpreadsheetFeed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG></ARG>

			<ARG></ARG>

		</ARGS>

	</TEMPLATE>


	<TEMPLATE NAME="Blogger">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

		<DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>
		
		<DEPENDENCY_COUNT>4</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="False">
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>This template creates a console application which interacts with the Blogger Data API to retrieve a list of all Blogs for a particular user.</DESCRIPTION>

		<FEED_URL>http://www.blogger.com/feeds/default/blogs</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.GoogleService</IMPORT>

			<IMPORT>com.google.gdata.data.Entry</IMPORT>

			<IMPORT>com.google.gdata.data.Feed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG>username</ARG>

			<ARG>password</ARG>

		</ARGS>

	</TEMPLATE>


	<TEMPLATE NAME="Calendar">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-calendar(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>
		
		<DEPENDENCY_COUNT>6</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="False">
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>This template creates a console application which interacts with the Google Calendar Data API to retrieve a list of all Google Calendars for a particular user.</DESCRIPTION>

		<FEED_URL>http://www.google.com/calendar/feeds/default/allcalendars/full</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.calendar.CalendarService</IMPORT>

			<IMPORT>com.google.gdata.data.calendar.CalendarEntry</IMPORT>

			<IMPORT>com.google.gdata.data.calendar.CalendarFeed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG>username</ARG>

			<ARG>password</ARG>

		</ARGS>

	</TEMPLATE>


	<TEMPLATE NAME="Picasa Web Albums">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-photos(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>
    
		<DEPENDENCY_COUNT>6</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="True">
    
      <EXT_DEPENDENCY NAME="Activation.jar">^activation(\-[1-9](\.[0-9])?(\.[0-9])?)?\.jar$</EXT_DEPENDENCY>
      
      <EXT_DEPENDENCY NAME="Mail.jar">^mail(\-[1-9](\.[0-9])?(\.[0-9])?)?\.jar$</EXT_DEPENDENCY>
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>This template creates a console application which interacts with the Picasa Web Album Data API to retrieve a list of all Albums for a particular user.</DESCRIPTION>

		<FEED_URL>http://picasaweb.google.com/data/feed/api/user/"+args[0]+"?kind=album</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.photos.PicasawebService</IMPORT>

			<IMPORT>com.google.gdata.data.photos.GphotoEntry</IMPORT>

			<IMPORT>com.google.gdata.data.photos.UserFeed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG>username</ARG>

			<ARG>password</ARG>

		</ARGS>

	</TEMPLATE>


	<TEMPLATE NAME="Contacts">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-contacts(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>  
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>

		<DEPENDENCY_COUNT>6</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="False">
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>This template creates a console application which interacts with the Google Contacts Data API to retrieve a list of all Contacts for a particular user.</DESCRIPTION>

		<FEED_URL>http://www.google.com/m8/feeds/contacts/"+args[0]+"@gmail.com/base</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.contacts.ContactsService</IMPORT>

			<IMPORT>com.google.gdata.data.contacts.ContactEntry</IMPORT>

			<IMPORT>com.google.gdata.data.contacts.ContactFeed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG>username</ARG>

			<ARG>password</ARG>

		</ARGS>

	</TEMPLATE>



	<TEMPLATE NAME="Documents">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-docs(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>  
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>

		<DEPENDENCY_COUNT>6</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="True">
    
      <EXT_DEPENDENCY NAME="Activation.jar">^activation(\-[1-9](\.[0-9])?(\.[0-9])?)?\.jar$</EXT_DEPENDENCY>
      
      <EXT_DEPENDENCY NAME="Mail.jar">^mail(\-[1-9](\.[0-9])?(\.[0-9])?)?\.jar$</EXT_DEPENDENCY>
    
    </THIRD_PARTY_DEPENDENCIES>		<DESCRIPTION>This template creates a console application which interacts with the Google Documents List Data API to retrieve a list of all Google Documents for a particular user.</DESCRIPTION>

		<FEED_URL>http://docs.google.com/feeds/documents/private/full</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.docs.DocsService</IMPORT>

			<IMPORT>com.google.gdata.data.docs.DocumentListEntry</IMPORT>

			<IMPORT>com.google.gdata.data.docs.DocumentListFeed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG>username</ARG>

			<ARG>password</ARG>

		</ARGS>

	</TEMPLATE>


	<TEMPLATE NAME="Google Apps Provisioning">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-appsforyourdomain(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>  
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>

		<DEPENDENCY_COUNT>6</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="False">
    
    </THIRD_PARTY_DEPENDENCIES>
    
		<DESCRIPTION>abcd</DESCRIPTION>

		<FEED_URL>http://spreadsheets.google.com/feeds/spreadsheets/private/full</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.spreadsheet.SpreadsheetService</IMPORT>

			<IMPORT>com.google.gdata.data.spreadsheet.SpreadsheetEntry</IMPORT>

			<IMPORT>com.google.gdata.data.spreadsheet.SpreadsheetFeed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG></ARG>

			<ARG></ARG>

		</ARGS>

	</TEMPLATE>


	<TEMPLATE NAME="Code Search">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-codesearch(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>  
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>

		<DEPENDENCY_COUNT>6</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="False">
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>This template creates a console application which interacts with the Google Code Search Data API to retrieve first ten Code Search results (if present) for a particular search query.</DESCRIPTION>

		<FEED_URL>http://www.google.com/codesearch/feeds/search?q="+args[0]+"</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.codesearch.CodeSearchService</IMPORT>

			<IMPORT>com.google.gdata.data.codesearch.CodeSearchEntry</IMPORT>

			<IMPORT>com.google.gdata.data.codesearch.CodeSearchFeed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG>search query</ARG>

		</ARGS>

	</TEMPLATE>


	<TEMPLATE NAME="Notebook">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
    
    </DEPENDENCIES>

		<DEPENDENCY_COUNT>4</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="False">
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>This template creates a console application which interacts	with the Google Notebook Data API to retrieve a list of all public Google Notebooks for a particular user.</DESCRIPTION>

		<FEED_URL>http://www.google.com/notebook/feeds/"+args[0]+"</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.GoogleService</IMPORT>

			<IMPORT>com.google.gdata.data.Entry</IMPORT>

			<IMPORT>com.google.gdata.data.Feed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG>user id (E.g. 14966091107146303894)</ARG>

		</ARGS>

	</TEMPLATE>


	<TEMPLATE NAME="YouTube">

		<FILE_NAME>GeneralTemplate.javajet</FILE_NAME>

    <DEPENDENCIES>
    
      <DEPENDENCY>^gdata\-youtube(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>  
      
      <DEPENDENCY>^gdata\-core\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-client(\-meta)?\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
      <DEPENDENCY>^gdata\-media\-[1-9]\.[0-9](\.[0-9])?\.jar$</DEPENDENCY>
      
    </DEPENDENCIES>

		<DEPENDENCY_COUNT>6</DEPENDENCY_COUNT>

    <THIRD_PARTY_DEPENDENCIES ISREQUIRED="True">
    
      <EXT_DEPENDENCY NAME="Activation.jar">^activation(\-[1-9](\.[0-9])?(\.[0-9])?)?\.jar$</EXT_DEPENDENCY>
      
      <EXT_DEPENDENCY NAME="Mail.jar">^mail(\-[1-9](\.[0-9])?(\.[0-9])?)?\.jar$</EXT_DEPENDENCY>
    
    </THIRD_PARTY_DEPENDENCIES>

		<DESCRIPTION>abcd</DESCRIPTION>

		<FEED_URL>http://spreadsheets.google.com/feeds/spreadsheets/private/full</FEED_URL>

		<IMPORTS>

			<IMPORT>com.google.gdata.client.spreadsheet.SpreadsheetService</IMPORT>

			<IMPORT>com.google.gdata.data.spreadsheet.SpreadsheetEntry</IMPORT>

			<IMPORT>com.google.gdata.data.spreadsheet.SpreadsheetFeed</IMPORT>

		</IMPORTS>

		<ARGS>

			<ARG></ARG>

		</ARGS>

	</TEMPLATE>


</TEMPLATECOLLECTION>
